parser: babel-eslint
env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
settings:
  react:
    pragma: 'React'
    version: '16'
plugins:
  - react
  - standard
rules:
  no-unused-vars: 0
  no-undef: 0
